name: Basic compile and test on Ubuntu and MacOS
on:
  push:
    branches:
      - 'bug_fixes'
      - 'master'
    paths:
      - '**.h'
      - '**.cpp'
      - 'bowtie2'
      - 'bowtie2-build'
      - 'bowtie2-inspect'
      - 'Makefile'
      - 'scripts/sim/**'
      - 'scripts/test/**'
  pull_request:
    branches:
      - 'master'
    paths:
      - '**.h'
      - '**.cpp'
      - 'bowtie2'
      - 'bowtie2-build'
      - 'bowtie2-inspect'
      - 'Makefile'
      - 'scripts/sim/**'
      - 'scripts/test/**'
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install zlib development files
        run: |
          sudo apt-get update
          sudo apt-get install zlib1g-dev
  linux:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - name: Run simple tests
        run: |
          make allall
          make simple-test
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run simple tests
        run: |
          make allall
          make simple-test
